### ISSUE TITLE
cannot download 

### ISSUE THREAD

**Issue by chantisnake** [Tlaster/iHentai#16]
![screenshot - copy 7](https://cloud.githubusercontent.com/assets/10100995/11817976/a44e387a-a325-11e5-9145-4dd94bec29dd.png)
![screenshot - copy 8](https://cloud.githubusercontent.com/assets/10100995/11817980/a74acc8c-a325-11e5-9c09-8ebbf1a9e176.png)

I can access ehentai just fine, but not through this app.

**Comment by Tlaster** [comment]
Sorry about that.
About the detail,it seems that you have no authority to view the large image if you are not logged in,which is important because the current version require it to show the image.I will fix it later.
But I have no idea about the reading part,everything works fine for me.

**Comment by Phantato** [comment]
I got the same problem at the preview page. And then I clicked into one picture, It said "loading the picture list". So I thought it might because that the network is too slow?

**Comment by chantisnake** [comment]
@Phantato I solved this issue by logging in. That works well

**Comment by Kadantte** [comment]
@chantisnake how did u login in t
