### ISSUE TITLE
Home page categories filter

### ISSUE THREAD

**Issue by Phantato** [Tlaster/iHentai#17]
Since the web page has a categories filter, and sometimes I just want to ignore some categories, hope there would be a filter not only for searching but also global.

**Comment by Tlaster** [comment]
Sorry for late.
You mean...search nothing but change the filter? or the setting in the settings page?

**Comment by Phantato** [comment]
Both is okay. I just wanna set it.(〃∀〃)

**Comment by Tlaster** [comment]
Well...
You can search nothing but change the filter right now, but as I'm not maintaining this project currently any improvements or enhancements will be super late.
