### ISSUE TITLE
gridview display error on back request

### ISSUE THREAD

**Issue by chantisnake** [Tlaster/iHentai#18]
when open a comic, click tag(or author), click search, and go into another comic, and press back button, the grid view will not display normally.

**Comment by Tlaster** [comment]
I'm thinking of refactoring the whole application, so currently I will not fix any bugs, sorry for that

**Comment by chantisnake** [comment]
i am thinking of creating a pr for dark theme... Since you will refactor it, I think I will wait. Can you inform me when you finished the refactor?

**Comment by Tlaster** [comment]
I'm planning to use Xamarin.Forms to do the refactoring because I want to bring EHTool to iOS for those don't want to jailbreak their device, it will take some time.
