### ISSUE TITLE
iHentai

### ISSUE THREAD

**Issue by Kadantte** [Tlaster/iHentai#27]
Any updates about iHentai ?

**Comment by Tlaster** [comment]
I've been busy the last two months, and [Shiba](https://github.com/Tlaster/Shiba) is still not ready yet, so iHentai will be updated once I've finished some key features for Shiba

**Comment by Kadantte** [comment]
I'm always seeing what you doing with Shiba, Anyway, I'm waiting for iHentai with Shiba :3
